apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-server
  labels:
    env: dev
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/api"
  labels:
    env: dev