apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-server
  labels:
    env: dev
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/"
  labels:
    env: dev