apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: myapp
patches:
- path: backend-deployment-patch.yaml
- path: backend-service-patch.yaml
- path: frontend-deployment-patch.yaml
- path: frontend-service-patch.yaml
images:
- name: 727646470302.dkr.ecr.ap-southeast-1.amazonaws.com/
  newName: 727646470302.dkr.ecr.ap-southeast-1.amazonaws.com/
- name: 727646470302.dkr.ecr.ap-southeast-1.amazonaws.com/mid2-backend
  newName: 727646470302.dkr.ecr.ap-southeast-1.amazonaws.com/mid2-backend
  newTag: abcdefg
- name: 727646470302.dkr.ecr.ap-southeast-1.amazonaws.com/mid2-frontend
  newName: 727646470302.dkr.ecr.ap-southeast-1.amazonaws.com/mid2-frontend
  newTag: hijklmn
